- name: Run nifi_transaction_and_aggregation python code
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/nifi_utility.py transaction_and_aggregation transaction_and_aggregation_parameters cQube_data_storage 4700"
  tags: [ install, update ]
