---
# for 4.0
- name: Stoping the server_side app
  become: yes
  shell: pm2 stop server_side
  tags: update

- name: Creating the server_side Directory for the installation
  file:
    path: "{{ base_dir }}/cqube/apis/node-api"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    recurse: yes
    state: directory
  tags: [ install, update ]

- name: copying server-side script
  copy:
    src: "../../apis/node-api/"
    dest: "{{base_dir}}/cqube/apis/node-api"
  tags: [ install, update ]

- name: NodeJS dependencies install
  npm:
    path: "{{base_dir}}/cqube/apis/node-api"
  tags: [ install, update ]

- name: Creating environmental variables
  file:
    path: "{{base_dir}}/cqube/apis/node-api/.env"
    state: touch
    mode: u+rw,g+rw,o+rw
  tags: [ install, update ]

- name: Loading required data inside .env file
  blockinfile:
    path: "{{base_dir}}/cqube/apis/node-api/.env"
    block: |
      STORAGE_SERVICE = "{% if storage_type == 'azure' %}AZURE_DATA_LAKE{% endif %}{% if storage_type == 's3' %}AWS_S3{% endif %}{% if storage_type == 'local' %}ON_PREMISE{% endif %}"
      AZURE_STORAGE_CONNECTION_STRING = "{{ azure_storage_connection_string }}"
      OUTPUT_CONTAINER = "{{ azure_output_container }}"
      INPUT_CONTAINER = "{{ azure_input_container }}"
      EMISSION_CONTAINER = "{{ azure_emission_container }}"
      PORT = 3000
      ACCESS_KEY_ID = "{{ s3_access_key }}"
      SECRET_ACCESS_KEY  = "{{ s3_secret_key }}"
      OUTPUT_BUCKET = "{{ s3_output_bucket }}"
      INPUT_BUCKET_NAME = "{{ s3_input_bucket }}"
      EMISSION_BUCKET = "{{ s3_emission_bucket }}"
      KEYCLOAK_HOST = "{{ protocol }}://{{ api_endpoint }}"
      KEYCLOAK_REALM = "{{ realm_name }}"
      KEYCLOAK_CLIENT = "{{ angular_app_client_id }}"
         
      KEYCLOAK_USER= "{{ keycloak_adm_user }}"
      PASSWORD= "{{ keycloak_adm_passwd }}"
      GRANT_TYPE= "password"
      BASE_DIR = "{{ base_dir }}"
      STORAGE_TYPE = "{{ storage_type }}"
      INPUT_DIR = "{{ input_directory }}"
      OUTPUT_DIR = "{{ output_directory }}"
      INPUT_DIRECTORY= "{{ input_directory }}"
      OUTPUT_DIRECTORY= "{{ output_directory }}"
      EMISSION_DIRECTORY= "{{ emission_directory }}"
      AZURE_EMISSION_STORAGE = "{{ azure_emission_container }}"
      AUTH_API = "{{ auth_api }}"
      DB_USER = "{{ db_user }}"
      SYSTEM_USERNAME = "{{ system_user_name }}"
      DB_PASSWORD = "{{ db_password }}"
      DB_NAME = "{{ db_name }}"
      DB_PORT = "5432"
  when: mode_of_installation != "localhost"
  tags: [ install, update ]

- name: Loading required data inside .env file (localhost)
  blockinfile:
    path: "{{base_dir}}/cqube/apis/node-api/.env"
    block: |
      STORAGE_SERVICE = "{% if storage_type == 'azure' %}AZURE_DATA_LAKE{% endif %}{% if storage_type == 's3' %}AWS_S3{% endif %}{% if storage_type == 'local' %}ON_PREMISE{% endif %}"
      AZURE_STORAGE_CONNECTION_STRING = "{{ azure_storage_connection_string }}"
      OUTPUT_CONTAINER = "{{ azure_output_container }}"
      INPUT_CONTAINER = "{{ azure_input_container }}"
      PORT = 3000
      ACCESS_KEY_ID = "{{ s3_access_key }}"
      SECRET_ACCESS_KEY  = "{{ s3_secret_key }}"
      OUTPUT_BUCKET = "{{ s3_output_bucket }}"
      INPUT_BUCKET_NAME = "{{ s3_input_bucket }}"
      EMISSION_BUCKET = "{{ s3_emission_bucket }}"
      KEYCLOAK_HOST = "{{ protocol }}://{{ api_endpoint }}:8080"
      KEYCLOAK_REALM = "{{ realm_name }}"
      KEYCLOAK_CLIENT = "{{ angular_app_client_id }}"
         
      KEYCLOAK_USER= "{{ keycloak_adm_user }}"
      PASSWORD= "{{ keycloak_adm_passwd }}"
      GRANT_TYPE= "password"
      BASE_DIR = "{{ base_dir }}"
      STORAGE_TYPE = "{{ storage_type }}"
      INPUT_DIR = "{{ input_directory }}"
      OUTPUT_DIR = "{{ output_directory }}"
      INPUT_DIRECTORY= "{{ input_directory }}"
      OUTPUT_DIRECTORY= "{{ output_directory }}"
      EMISSION_DIRECTORY= "{{ emission_directory }}"
      AUTH_API = "{{ auth_api }}"
      DB_USER = "{{ db_user }}"
      SYSTEM_USERNAME = "{{ system_user_name }}"
      DB_PASSWORD = "{{ db_password }}"
      DB_NAME = "{{ db_name }}"
      DB_PORT = "5432"
  when: mode_of_installation == "localhost"
  tags: [ install, update ]
