---
- name: Creating a Directory to store the log files
  file:
    path: "{{ base_dir }}/cqube/logs"
    state: absent
  tags: install

- name: Creating a Directory to store the log files
  file: 
    path: "{{ base_dir }}/cqube/logs"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    state: directory
  tags: [ install, update ]

- name: Create a symbolic link
  file:
    src: "{{ item.src }}"
    dest: "{{ base_dir }}/cqube/logs/{{ item.dest }}"
    state: link
    force: yes
    follow: false
  with_items:
    - { src: "{{base_dir}}/cqube/nifi/nifi/logs/nifi-app.log", dest: "nifi-app.log" }
    - { src: "{{base_dir}}/cqube/nifi/nifi/logs/nifi-bootstrap.log", dest: "nifi-bootstrap.log" }
    - { src: "/var/log/postgresql/postgresql-10-main.log", dest: "postgresql-10-main.log" }
    - { src: "{{base_dir}}/cqube/emission_app/python/access.log", dest: "emission_app-access.log" }
    - { src: "{{base_dir}}/cqube/emission_app/python/error.log", dest: "emission_app-error.log" }
    - { src: "/home/{{system_user_name}}/.pm2/logs/dashboard-error.log", dest: "dashboard-error.log"}
    - { src: "/home/{{system_user_name}}/.pm2/logs/dashboard-out.log", dest: "dashboard-out.log"}
    - { src: "/home/{{system_user_name}}/.pm2/logs/admin-dashboard-error.log", dest: "admin-dashboard-error.log"}
    - { src: "/home/{{system_user_name}}/.pm2/logs/admin-dashboard-out.log", dest: "admin-dashboard-out.log"}
    - { src: "/home/{{system_user_name}}/.pm2/logs/core-api-error.log", dest: "core-api-error.log"}
    - { src: "/home/{{system_user_name}}/.pm2/logs/core-api-out.log", dest: "core-api-out.log"}
    - { src: "/home/{{system_user_name}}/.pm2/logs/dashboard-api-error.log", dest: "dashboard-api-error.log"}
    - { src: "/home/{{system_user_name}}/.pm2/logs/dashboard-api-out.log", dest: "dashboard-api-out.log"}
    - { src: "/home/{{system_user_name}}/.pm2/logs/admin-api-error.log", dest: "admin-api-error.log"}
    - { src: "/home/{{system_user_name}}/.pm2/logs/admin-api-out.log", dest: "admin-api-out.log"}
    - { src: "/home/{{system_user_name}}/.pm2/logs/auth-api-error.log", dest: "auth-api-error.log"}
    - { src: "/home/{{system_user_name}}/.pm2/logs/auth-api-out.log", dest: "auth-api-out.log"}
    - { src: "/var/log/syslog", dest: "syslog"}
    - { src: "{{base_dir}}/cqube/keycloak/standalone/log/server.log", dest: "server.log"}
    - { src: "{{base_dir}}/cqube/keycloak/standalone/log/audit.log", dest: "audit.log"}
  tags: [ install, update ]
