- name: checking process of pm2 server_side
  become: yes
  shell: pm2 id auth-api
  register: pm2_output
  tags: [ install, update ]

- name: checking the existing pm2 processes if running
  shell: pm2 delete auth-api
  when: pm2_output.stdout != "[]"
  ignore_errors: True
  become: yes
  tags: [ install, update ]

- name: Starting NodeJS application
  become: yes
  shell: pm2 start node --name auth-api -- . &
  args:
    chdir: "{{ base_dir }}/cqube/apis/auth-api"
  tags: [ install, update ]
