---
- name: copy the database backup script to base directory
  template:
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: 0644
    src: frequent_database_backup.sh.j2
    dest: "{{ base_dir }}/cqube/postgres/frequent_database_backup.sh"
  when: db_backup_scheduling == true
  tags: [ install, update ]
