---
- name: Update apt cache - Kong
  become: yes
  apt:
    update_cache: true

- name: Install Kong Dependencies
  become: yes
  apt:
    name: "{{ kong_dependencies }}"
    state: present

- name: Add BinTray deb repository
  become: yes
  shell:  echo "deb [trusted=yes] https://download.konghq.com/gateway-2.x-ubuntu-$(lsb_release -sc)/ default all" | sudo tee /etc/apt/sources.list.d/kong.list

- name: "Install Kong"
  become: yes
  apt:
    update_cache: true
    name: "kong"
    force: yes  
    state: present

- name: Ensure database is created
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ kong_db_name}}"
    encoding: 'UTF-8'
    state: present

- name: Ensure Kong DB user
  become: true
  become_user: postgres
  postgresql_user:
    db: "{{ kong_db_name }}"
    name: "{{ kong_db_user }}"
    password: "{{ kong_db_password }}"
    priv: "ALL"
    state: present

- name: Inserting configuration in pg_hba.conf file
  lineinfile:
    path: /etc/postgresql/10/main/pg_hba.conf
    line: "host    all     kong       127.0.0.1/32      trust"
    insertafter: "host    all             postgres             127.0.0.1/32            trust"

- name: reload pghba
  shell: psql "host=localhost dbname={{ db_name }} user={{ db_user }} password={{ db_password }}" -c "SELECT pg_reload_conf();"

- name: postgresql systemd service restart
  service:
    name: postgresql
    state: restarted

- name: Write kong config
  become: yes
  template:
    dest: /etc/kong/kong.conf
    group: root
    mode: 0644
    owner: root
    src: kong.conf.j2

- name: kong migrations bootstrap
  shell: kong migrations bootstrap -c /etc/kong/kong.conf

- name: kong systemd setup
  template:
    owner: root
    group: root
    mode: 0644
    src: kong.service.j2
    dest: /etc/systemd/system/kong.service

- name: reload systemd
  become: yes
  shell: systemctl daemon-reload

- name: kong systemd service enable and start
  service: 
    name: kong
    enabled: yes
    state: started

- name: Install requests
  pip:
    name: requests
    executable: pip3
