- name: Run diksha python code
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/nifi_utility.py diksha_transformer diksha_parameters cQube_data_storage 4662 {{ storage_type }}"
  tags: [ install, update ]

- name: Enable diksha ETB API
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/nifi_utility.py diksha_transformer {{ storage_type }} ETB API"                                         
  tags: [ install, update ]

- name: Enable diksha TPD API
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/nifi_utility.py diksha_transformer {{ storage_type }} TPD API"                                         
  tags: [ install, update ]

- name: Run diksha custom python code
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/nifi_utility.py diksha_transformer_custom diksha_parameters cQube_data_storage 0"
  tags: [ install, update ]
